### PR TITLE
Add Form

### PR DESCRIPTION
**Pull request by heintayzar-hm**
Add form and its css file.
Test with Fromspree.

Thank you for viewing PR

### CODE REVIEW

**Review by aimalamiri — CHANGES_REQUESTED** [review]
Hi @heintayzar-hm, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

AlmostThereReachGIF

## Highlights

- The form section is designed very well ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by heintayzar-hm** [comment]
@aimalamiri What is my required changes? It is not appearing in the comments

**Review by ahmetbozaci — COMMENTED** [review]
Hello @heintayzar-hm @waseemqureshi2020   👋,

_This is an additional review as a result of the second opinion request._

- Everything is awesome in your project, you follow the all requirement in this milestone.

Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)


Keep rocking 🚀! // can be customized

**Comment by ahmetbozaci** [comment]
> Hello @heintayzar-hm @waseemqureshi2020 wave,
> 
> _This is an additional review as a result of the second opinion request._
> 
> * Everything is awesome in your project, you follow the all requirement in this milestone.
> 
> Please ask for another review in your Dashboard and the next Code Reviewer will mark it as approved right away :)
> 
> Keep rocking rocket! // can be customized

_Kindly ignore my last message ı also not notice that line._
@heintayzar-hm Like the last code reviewer kindly add the line to follow the design.
image

**Comment by heintayzar-hm** [comment]
Yes thank you

**Review by christianbiring1 — APPROVED** [review]
Hi @heintayzar-hm , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS: APPROVED :tada: 
imageswelljob

## Highlights
- [ ] All linters tests are green
- [ ] Descriptive PR `title` and `summary`
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by heintayzar-hm** [comment]
I think you should see my review again. You requested changes but no
changes are commented.

**Pull request merged**
